data:
  dataset: sick_euthyroid
  dataset_path: configs/sick_euthyroid/dataset.csv
  target_column: target
experiment:
  tags:
  - sick_euthyroid
  name: sick_euthyroid
model:
  type: RandomForestClassifier
  n_estimators: 15
  min_samples_split: 3
  min_impurity_decrease: 0.0
  max_features: 0.7
  max_depth: 8
  criterion: entropy
