data:
  dataset: yeast_me2
  dataset_path: configs/yeast_me2/dataset.csv
  target_column: target
experiment:
  tags:
  - yeast_me2
  name: yeast_me2
model:
  type: RandomForestClassifier
  n_estimators: 15
  min_samples_split: 4
  min_impurity_decrease: 0.0
  max_features: 0.7
  max_depth: 8
  criterion: gini
