data:
  dataset: abalone
  dataset_path: configs/abalone/dataset.csv
  target_column: target
experiment:
  tags:
  - abalone
  name: abalone
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_samples_split: 7
  min_impurity_decrease: 0.1
  max_features: 0.3
  max_depth: 8
  criterion: entropy
