data:
  dataset: obesity_levels
  dataset_path: configs/obesity_levels/dataset.csv
  target_column: NObeyesdad
  categorical_features:
  - Gender
  - CALC
  - FAVC
  - SCC
  - SMOKE
  - family_history_with_overweight
  - CAEC
  - MTRANS
experiment:
  tags:
  - obesity_levels
  name: obesity_levels
methods:
  dpg:
    overgeneration_factor: 20
  _default:
    actionability:
      Age: non_decreasing
      Gender: no_change
      Height: no_change
      family_history_with_overweight: no_change
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_impurity_decrease: 0.0
  max_features: null
  max_depth: 6
